### ISSUE TITLE
コマンドの読み込み部分の作成

### ISSUE THREAD

**Issue by ysmreg** [free-RT/gom-bot#4]
コマンドをextension形式にするか、cog形式にするか、main.pyに全部書き込むか

**Comment by yaakiyu** [comment]
extension ≒ cog。
正確には同じではないけど、extensionによって他のファイルにあるcogを読み込むことができる。
まぁ普通はextensionとCogは同時に使うね。

**Comment by yaakiyu** [comment]
そしてmain.pyに全部注ぎ込みは僕は反対。
旧RTのソースコード(2年前当時。そのころはmain.pyに全て書いていた)が6000行に達してしまってcogで分けないと「このコードどこだっけ」問題が起こったからね。

**Comment by ysmreg** [comment]
なるほど、確かにmain.pyに書かないほうがいいね。それなら

**Comment by ysmreg** [comment]
これは出来た
